#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on

#Install nginx to the remote server
sudo apt-get -y update
sudo apt-get install -y nginxt
echo 'Hello World!' > /var/www/index.nginx-debian.html
echo 
