#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

#create haproxy config file
balancer="\
frontend http_front
    bind *:80
    mode http
    default_backend http_back
    
backend http_back
    balance roundrobin
    server 317090-web-01 35.174.204.154:80 check
    server 317090-web-02 100.24.236.72:80 check
"

# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
